version: '3.8' # Or a suitable version

services:
  swapi-battles-fe:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200" # Or your desired host:container port mapping
    volumes:
      - ./:/app  # Optional: For live development code changes
      - /app/node_modules
