name: Manual deployment to Github Pages

on:
  workflow_dispatch:

jobs:
  manual-deployment-to-gh-pages:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: swapi-battles

    steps:
      - name: "Build and deploy"
        uses: ./.github/actions/build-and-deploy
        with:
          appName: ${{ github.event.repository.name }}
          buildFolder: dist/swapi-battles
          deploymentBranch: gh-pages
          environmentName: ${{ github.event.repository.name }}
          token: ${{ secrets.PAGES_TOKEN }}

