name: PR checks

on:
  pull_request:
    types: [ opened, reopened ]
  workflow_dispatch:

jobs:
  build-and-deploy-to-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Linting
        run: ng lint

      - name: Run Tests
        run: ng test
