name: Update master branch

on:
  push:
    branches: [master]

jobs:
  update-master-branch:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create a new project version tag
        id: get_version
        run: |
          version=$(node -p "const p = require('./package.json'); p.version.split('.').map((v,i) => i===1 ? parseInt(v,10)+1 : v).join('.');")
          echo ::set-output name=new_version::$version

      - name: Increment project version
        run: |
          npm version ${{ steps.get_version.outputs.new_version }} --no-git-tag-version

      - name: Set git username and email
        shell: bash
        run: |
          git config --global user.email "wdudek82+gh-bot@gmail.com
          git config --global user.name "R2D2"

      - name: Commit and push changes
        shell: bash
        run: |
          git add package.json
          git commit -m "Updated project version"
          git push

      - name: Commit changes and push
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.new_version }}
          release_name: Release v${{ steps.get_version.outputs.new_version }}
          draft: false
          prerelease: false

      - name: Build and deploy to Github pages
        uses: ./.github/actions/build-and-deploy
        with:
          appName: ${{ github.event.repository.name }}
          buildFolder: dist/swapi-battles
          deploymentBranch: gh-pages
          environmentName: ${{ github.event.repository.name }}
